import { Writable } from "svelte/store";

declare module 'svelte-contracts' {
    export const USDT: import("svelte/store").Writable<string | undefined>;
    export const USDC: import("svelte/store").Writable<string | undefined>;
    export const SHIB: import("svelte/store").Writable<string | undefined>;
    export const MATIC: import("svelte/store").Writable<string | undefined>;
    export const BUSD: import("svelte/store").Writable<string | undefined>;
    export const CRO: import("svelte/store").Writable<string | undefined>;
    export const WBTC: import("svelte/store").Writable<string | undefined>;
    export const UNI: import("svelte/store").Writable<string | undefined>;
    export const LTC: import("svelte/store").Writable<string | undefined>;
    export const UST: import("svelte/store").Writable<string | undefined>;
    export const LINK: import("svelte/store").Writable<string | undefined>;
    export const DAI: import("svelte/store").Writable<string | undefined>;
    export const NEAR: import("svelte/store").Writable<string | undefined>;
    export const BCH: import("svelte/store").Writable<string | undefined>;
    export const ATOM: import("svelte/store").Writable<string | undefined>;
    export const TRX: import("svelte/store").Writable<string | undefined>;
    export const FTM: import("svelte/store").Writable<string | undefined>;
    export const MANA: import("svelte/store").Writable<string | undefined>;
    export const AXS: import("svelte/store").Writable<string | undefined>;
    export const FTT: import("svelte/store").Writable<string | undefined>;
    export const SAND: import("svelte/store").Writable<string | undefined>;
    export const FIL: import("svelte/store").Writable<string | undefined>;
    export const BTCB: import("svelte/store").Writable<string | undefined>;
    export const ETC: import("svelte/store").Writable<string | undefined>;
    export const XTZ: import("svelte/store").Writable<string | undefined>;
    export const AAVE: import("svelte/store").Writable<string | undefined>;
    export const GRT: import("svelte/store").Writable<string | undefined>;
    export const LRC: import("svelte/store").Writable<string | undefined>;
    export const contracts: import("svelte/store").Readable<{
        USDT: string | undefined;
        USDC: string | undefined;
        SHIB: string | undefined;
        MATIC: string | undefined;
        BUSD: string | undefined;
        WBTC: string | undefined;
        CRO: string | undefined;
        UNI: string | undefined;
        LTC: string | undefined;
        UST: string | undefined;
        LINK: string | undefined;
        DAI: string | undefined;
        NEAR: string | undefined;
        BCH: string | undefined;
        ATOM: string | undefined;
        TRX: string | undefined;
        FTM: string | undefined;
        MANA: string | undefined;
        AXS: string | undefined;
        FTT: string | undefined;
        SAND: string | undefined;
        FIL: string | undefined;
        BTCB: string | undefined;
        ETC: string | undefined;
        XTZ: string | undefined;
        AAVE: string | undefined;
        GRT: string | undefined;
        LRC: string | undefined;
    }>; 
}